apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadataName }}
  labels:
    run: {{ .Values.metadataLabel }}
spec:
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.metadataLabel }}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.metadataLabel }}
    spec:
      imagePullSecrets:
        - name: docker-reg
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
            limits:
              cpu: "1"
              memory: "128Mi"