apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ .Values.metadataName }}
  labels:
    run: {{ .Values.metadataLabel }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.selectorLabels }}
