name: ci
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # - name: Get the version
      #   id: tag
      #   run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})

      # - name: Build the tagged Docker image
      #   run: docker build -t parth10/dotnetapp:${{steps.tag.outputs.tag}} .

      # - name: Push the tagged Docker image
      #   run: docker push parth10/dotnetapp:${{steps.tag.outputs.tag}}

      # - name: Build the latest Docker image
      #   run: docker build -t parth10/dotnetapp:latest .

      # - name: Push the latest Docker image
      #   run: docker push parth10/dotnetapp:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/actions/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account show