name: ci
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the version
        id: tag
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})

      - name: Build the tagged Docker image
        run: docker build -t parth10/dotnetapp:${{steps.tag.outputs.tag}} .

      - name: Push the tagged Docker image
        run: docker push parth10/dotnetapp:${{steps.tag.outputs.tag}}

      - name: Build the latest Docker image
        run: docker build -t parth10/dotnetapp:latest .

      - name: Push the latest Docker image
        run: docker push parth10/dotnetapp:latest
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     # script: echo ${{ secrets.GITHUB_RUN_ID }}
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/dotnetapp:latest, ${{ secrets.DOCKER_USERNAME }}/dotnetapp:$GITHUB_SHA